name: utama_portal
description: "Aplikasi portal utama untuk desktop."

publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  
  file_picker: ^8.0.5
  
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.3.0
  package_info_plus: ^5.0.1
  version: ^3.0.2
  uuid: ^4.4.0
  win32: ^5.5.0
  process_run: ^0.12.0 
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  archive: ^3.5.1
  flutter_svg: ^2.0.10+1
  ffi: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/bg/


flutter_launcher_icons:
  windows:
    generate: true
    
    image_path: "assets/icons/icon.png"
    
    icon_size: 256 

  
  android: false
  ios: false
  web:
    generate: false
  macos:
    generate: false

dependency_overrides:
  web: ^0.5.1

